// <auto-generated />
using System;
using Labb2AngularAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AngularAPI.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20221013064259_person")]
    partial class person
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik, Skor & Klädsel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Livsmedel & Skor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Filmer & Leksaker"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Böcker"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Musik, Datorer & Musik"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hem & Livsmedel"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hem, Smycken & Musik"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Leksaker"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Trädgård"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Trädgård & Smycken"
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Backvägen 72",
                            DepartmentId = 6,
                            FirstName = "Meggie",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 57813
                        },
                        new
                        {
                            Id = 2,
                            Address = "Övre Idrottsgatan 1",
                            DepartmentId = 1,
                            FirstName = "Ethyl",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 46532
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bonnies Väg 12",
                            DepartmentId = 5,
                            FirstName = "Laurine",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 38524
                        },
                        new
                        {
                            Id = 4,
                            Address = "Övre Skolallén 1",
                            DepartmentId = 5,
                            FirstName = "Bernadine",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 39515
                        },
                        new
                        {
                            Id = 5,
                            Address = "Johanssons Gata 16",
                            DepartmentId = 8,
                            FirstName = "Jackson",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 36816
                        },
                        new
                        {
                            Id = 6,
                            Address = "Trevors Väg 966",
                            DepartmentId = 6,
                            FirstName = "Alexandrine",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 52713
                        },
                        new
                        {
                            Id = 7,
                            Address = "Norra Storgränden 9",
                            DepartmentId = 3,
                            FirstName = "Pearl",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 50988
                        },
                        new
                        {
                            Id = 8,
                            Address = "Alyces Gata 23",
                            DepartmentId = 8,
                            FirstName = "Norris",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 46579
                        },
                        new
                        {
                            Id = 9,
                            Address = "Nilssons Väg 8",
                            DepartmentId = 8,
                            FirstName = "Suzanne",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 54057
                        },
                        new
                        {
                            Id = 10,
                            Address = "Olssons Väg 8",
                            DepartmentId = 2,
                            FirstName = "Mac",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 57194
                        },
                        new
                        {
                            Id = 11,
                            Address = "Gengärdet 9",
                            DepartmentId = 10,
                            FirstName = "Kaylee",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 49268
                        },
                        new
                        {
                            Id = 12,
                            Address = "Undre Ekallén 88",
                            DepartmentId = 3,
                            FirstName = "Alessandro",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 34249
                        },
                        new
                        {
                            Id = 13,
                            Address = "Nilssons Väg 280",
                            DepartmentId = 9,
                            FirstName = "Kurt",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 58424
                        },
                        new
                        {
                            Id = 14,
                            Address = "Ringallén 41",
                            DepartmentId = 7,
                            FirstName = "Francis",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 42345
                        },
                        new
                        {
                            Id = 15,
                            Address = "Nilssons Gata 52",
                            DepartmentId = 4,
                            FirstName = "Pascale",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 46128
                        },
                        new
                        {
                            Id = 16,
                            Address = "Ringgatan 581",
                            DepartmentId = 3,
                            FirstName = "Lavina",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 34263
                        },
                        new
                        {
                            Id = 17,
                            Address = "Aspgränden 8",
                            DepartmentId = 6,
                            FirstName = "Arnulfo",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 57488
                        },
                        new
                        {
                            Id = 18,
                            Address = "Övre Aspallén 88",
                            DepartmentId = 6,
                            FirstName = "Marcella",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 37387
                        },
                        new
                        {
                            Id = 19,
                            Address = "Norra Ängsallén 84",
                            DepartmentId = 4,
                            FirstName = "Eino",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 33316
                        },
                        new
                        {
                            Id = 20,
                            Address = "Backgatan 512",
                            DepartmentId = 10,
                            FirstName = "Al",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 49675
                        },
                        new
                        {
                            Id = 21,
                            Address = "Ängsgränden 6",
                            DepartmentId = 2,
                            FirstName = "Donald",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 47111
                        },
                        new
                        {
                            Id = 22,
                            Address = "Enas Gata 81",
                            DepartmentId = 2,
                            FirstName = "Jeffery",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 43525
                        },
                        new
                        {
                            Id = 23,
                            Address = "Övre Industrigatan 431",
                            DepartmentId = 5,
                            FirstName = "Giles",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 40641
                        },
                        new
                        {
                            Id = 24,
                            Address = "Karlies Gata 1",
                            DepartmentId = 1,
                            FirstName = "Edwardo",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 39300
                        },
                        new
                        {
                            Id = 25,
                            Address = "Karlssons Väg 924",
                            DepartmentId = 6,
                            FirstName = "Abigayle",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 45878
                        },
                        new
                        {
                            Id = 26,
                            Address = "Västra Björkgatan 8",
                            DepartmentId = 7,
                            FirstName = "Columbus",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 37820
                        },
                        new
                        {
                            Id = 27,
                            Address = "Gustafssons Gata 155",
                            DepartmentId = 5,
                            FirstName = "Kennith",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 33372
                        },
                        new
                        {
                            Id = 28,
                            Address = "Calistas Gata 6",
                            DepartmentId = 1,
                            FirstName = "Anika",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 40335
                        },
                        new
                        {
                            Id = 29,
                            Address = "Åkerallén 14",
                            DepartmentId = 6,
                            FirstName = "Tobin",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 46021
                        },
                        new
                        {
                            Id = 30,
                            Address = "Reeces Väg 983",
                            DepartmentId = 5,
                            FirstName = "Darien",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 45514
                        },
                        new
                        {
                            Id = 31,
                            Address = "Nilssons Väg 6",
                            DepartmentId = 3,
                            FirstName = "Garret",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 57069
                        },
                        new
                        {
                            Id = 32,
                            Address = "Skogsvägen 1",
                            DepartmentId = 10,
                            FirstName = "Malcolm",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 39077
                        },
                        new
                        {
                            Id = 33,
                            Address = "Karlssons Gata 61",
                            DepartmentId = 3,
                            FirstName = "Nellie",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 41740
                        },
                        new
                        {
                            Id = 34,
                            Address = "Olssons Väg 60",
                            DepartmentId = 8,
                            FirstName = "America",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 53797
                        },
                        new
                        {
                            Id = 35,
                            Address = "Keegans Väg 5",
                            DepartmentId = 8,
                            FirstName = "Orlo",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 44483
                        },
                        new
                        {
                            Id = 36,
                            Address = "Skogsgatan 549",
                            DepartmentId = 8,
                            FirstName = "Karelle",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 32215
                        },
                        new
                        {
                            Id = 37,
                            Address = "Östra Backallén 5",
                            DepartmentId = 9,
                            FirstName = "Stephany",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 47741
                        },
                        new
                        {
                            Id = 38,
                            Address = "Olssons Gata 72",
                            DepartmentId = 3,
                            FirstName = "Lamont",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 56705
                        },
                        new
                        {
                            Id = 39,
                            Address = "Raphaels Väg 441",
                            DepartmentId = 7,
                            FirstName = "Cameron",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 57147
                        },
                        new
                        {
                            Id = 40,
                            Address = "Aimees Väg 078",
                            DepartmentId = 10,
                            FirstName = "Candice",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 52417
                        },
                        new
                        {
                            Id = 41,
                            Address = "Idrottsallén 212",
                            DepartmentId = 8,
                            FirstName = "Priscilla",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 43242
                        },
                        new
                        {
                            Id = 42,
                            Address = "Skolgärdet 626",
                            DepartmentId = 1,
                            FirstName = "Danika",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 39464
                        },
                        new
                        {
                            Id = 43,
                            Address = "Kevens Väg 882",
                            DepartmentId = 8,
                            FirstName = "Garret",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 38760
                        },
                        new
                        {
                            Id = 44,
                            Address = "Ambers Gata 583",
                            DepartmentId = 9,
                            FirstName = "Vesta",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 53183
                        },
                        new
                        {
                            Id = 45,
                            Address = "Lylas Väg 188",
                            DepartmentId = 5,
                            FirstName = "Alicia",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 49623
                        },
                        new
                        {
                            Id = 46,
                            Address = "Orens Väg 43",
                            DepartmentId = 5,
                            FirstName = "Selmer",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 40627
                        },
                        new
                        {
                            Id = 47,
                            Address = "Östra Gengärdet 354",
                            DepartmentId = 9,
                            FirstName = "Effie",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 38011
                        },
                        new
                        {
                            Id = 48,
                            Address = "Kyrkogränden 982",
                            DepartmentId = 8,
                            FirstName = "Stefanie",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 53321
                        },
                        new
                        {
                            Id = 49,
                            Address = "Åkergärdet 844",
                            DepartmentId = 8,
                            FirstName = "Malvina",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 49101
                        },
                        new
                        {
                            Id = 50,
                            Address = "Västra Nygärdet 974",
                            DepartmentId = 9,
                            FirstName = "Jace",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 56103
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.HasOne("Labb2AngularAPI.Models.Person", null)
                        .WithMany("Department")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
