// <auto-generated />
using System;
using Labb2AngularAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AngularAPI.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20221011114410_editdepartment")]
    partial class editdepartment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Klädsel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Musik & Elektronik"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Musik, Livsmedel & Trädgård"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Datorer & Verktyg"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Filmer, Trädgård & Smycken"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Trädgård & Livsmedel"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hälsa & Trädgård"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Skönhet, Spel & Verktyg"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Filmer, Musik & Spel"
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Strandallén 183",
                            DepartmentId = 5,
                            FirstName = "Filomena",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 33760
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nilssons Gata 9",
                            DepartmentId = 1,
                            FirstName = "Lennie",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 36242
                        },
                        new
                        {
                            Id = 3,
                            Address = "Nilssons Väg 696",
                            DepartmentId = 9,
                            FirstName = "Elisa",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 58107
                        },
                        new
                        {
                            Id = 4,
                            Address = "Reynas Gata 919",
                            DepartmentId = 9,
                            FirstName = "Olen",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 54969
                        },
                        new
                        {
                            Id = 5,
                            Address = "Bessies Gata 34",
                            DepartmentId = 10,
                            FirstName = "Ayana",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 34983
                        },
                        new
                        {
                            Id = 6,
                            Address = "Västra Kyrkvägen 93",
                            DepartmentId = 5,
                            FirstName = "Margie",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 54664
                        },
                        new
                        {
                            Id = 7,
                            Address = "Undre Villagatan 7",
                            DepartmentId = 8,
                            FirstName = "Walker",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 51664
                        },
                        new
                        {
                            Id = 8,
                            Address = "Genvägen 6",
                            DepartmentId = 6,
                            FirstName = "Kelsi",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 33115
                        },
                        new
                        {
                            Id = 9,
                            Address = "Jovanys Gata 4",
                            DepartmentId = 2,
                            FirstName = "Yasmin",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 34729
                        },
                        new
                        {
                            Id = 10,
                            Address = "Karlssons Gata 7",
                            DepartmentId = 3,
                            FirstName = "Elmer",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 51924
                        },
                        new
                        {
                            Id = 11,
                            Address = "Guadalupes Gata 289",
                            DepartmentId = 9,
                            FirstName = "Shanny",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 52146
                        },
                        new
                        {
                            Id = 12,
                            Address = "Lorenzas Gata 063",
                            DepartmentId = 6,
                            FirstName = "Dax",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 36405
                        },
                        new
                        {
                            Id = 13,
                            Address = "Johanssons Gata 65",
                            DepartmentId = 2,
                            FirstName = "Andre",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 39580
                        },
                        new
                        {
                            Id = 14,
                            Address = "Norra Ekgränden 7",
                            DepartmentId = 8,
                            FirstName = "Carole",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 32379
                        },
                        new
                        {
                            Id = 15,
                            Address = "Larssons Väg 3",
                            DepartmentId = 5,
                            FirstName = "Crystal",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 38043
                        },
                        new
                        {
                            Id = 16,
                            Address = "Erikssons Gata 691",
                            DepartmentId = 4,
                            FirstName = "Lilly",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 47518
                        },
                        new
                        {
                            Id = 17,
                            Address = "Asas Väg 5",
                            DepartmentId = 1,
                            FirstName = "Demond",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 54380
                        },
                        new
                        {
                            Id = 18,
                            Address = "Norra Ängsallén 01",
                            DepartmentId = 3,
                            FirstName = "Hertha",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 46885
                        },
                        new
                        {
                            Id = 19,
                            Address = "Svenssons Gata 3",
                            DepartmentId = 5,
                            FirstName = "Sarai",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 55701
                        },
                        new
                        {
                            Id = 20,
                            Address = "Parkgatan 131",
                            DepartmentId = 2,
                            FirstName = "Vaughn",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 41944
                        },
                        new
                        {
                            Id = 21,
                            Address = "Ringgränden 314",
                            DepartmentId = 5,
                            FirstName = "Russ",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 46449
                        },
                        new
                        {
                            Id = 22,
                            Address = "Kyrkgärdet 58",
                            DepartmentId = 1,
                            FirstName = "Cecelia",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 34166
                        },
                        new
                        {
                            Id = 23,
                            Address = "Östra Storgatan 628",
                            DepartmentId = 8,
                            FirstName = "Ariel",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 56280
                        },
                        new
                        {
                            Id = 24,
                            Address = "Undre Fabriksgatan 559",
                            DepartmentId = 9,
                            FirstName = "Halie",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 51910
                        },
                        new
                        {
                            Id = 25,
                            Address = "Idrottsgränden 9",
                            DepartmentId = 4,
                            FirstName = "Ally",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 35907
                        },
                        new
                        {
                            Id = 26,
                            Address = "Idrottsgränden 853",
                            DepartmentId = 10,
                            FirstName = "Arch",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 48438
                        },
                        new
                        {
                            Id = 27,
                            Address = "Östra Parkgränden 818",
                            DepartmentId = 9,
                            FirstName = "Aurelia",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 49547
                        },
                        new
                        {
                            Id = 28,
                            Address = "Orions Väg 1",
                            DepartmentId = 9,
                            FirstName = "Erik",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 51277
                        },
                        new
                        {
                            Id = 29,
                            Address = "Darwins Gata 96",
                            DepartmentId = 8,
                            FirstName = "Rodolfo",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 43626
                        },
                        new
                        {
                            Id = 30,
                            Address = "Gustafssons Väg 84",
                            DepartmentId = 8,
                            FirstName = "Daphnee",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 44798
                        },
                        new
                        {
                            Id = 31,
                            Address = "Gustafssons Väg 799",
                            DepartmentId = 10,
                            FirstName = "Katlyn",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 51820
                        },
                        new
                        {
                            Id = 32,
                            Address = "Nilssons Väg 00",
                            DepartmentId = 3,
                            FirstName = "Fiona",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 56450
                        },
                        new
                        {
                            Id = 33,
                            Address = "Undre Ekgatan 505",
                            DepartmentId = 8,
                            FirstName = "Jacynthe",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 46003
                        },
                        new
                        {
                            Id = 34,
                            Address = "Rexs Väg 792",
                            DepartmentId = 7,
                            FirstName = "Veronica",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 56314
                        },
                        new
                        {
                            Id = 35,
                            Address = "Västra Nygränden 149",
                            DepartmentId = 4,
                            FirstName = "Rex",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 53395
                        },
                        new
                        {
                            Id = 36,
                            Address = "Augustines Gata 3",
                            DepartmentId = 6,
                            FirstName = "Abner",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 47275
                        },
                        new
                        {
                            Id = 37,
                            Address = "Södra Åkervägen 3",
                            DepartmentId = 5,
                            FirstName = "Reyes",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 46999
                        },
                        new
                        {
                            Id = 38,
                            Address = "Södra Idrottsgärdet 1",
                            DepartmentId = 9,
                            FirstName = "Timothy",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 57127
                        },
                        new
                        {
                            Id = 39,
                            Address = "Skogsgränden 263",
                            DepartmentId = 6,
                            FirstName = "Janet",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 45953
                        },
                        new
                        {
                            Id = 40,
                            Address = "Östra Åkergatan 34",
                            DepartmentId = 9,
                            FirstName = "Donnell",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 38000
                        },
                        new
                        {
                            Id = 41,
                            Address = "Nilssons Gata 643",
                            DepartmentId = 8,
                            FirstName = "Yasmin",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 45313
                        },
                        new
                        {
                            Id = 42,
                            Address = "Västra Industrigärdet 8",
                            DepartmentId = 2,
                            FirstName = "Chester",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 33079
                        },
                        new
                        {
                            Id = 43,
                            Address = "Nilssons Gata 4",
                            DepartmentId = 8,
                            FirstName = "Rosalia",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 37554
                        },
                        new
                        {
                            Id = 44,
                            Address = "Odas Väg 903",
                            DepartmentId = 2,
                            FirstName = "Ben",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 52951
                        },
                        new
                        {
                            Id = 45,
                            Address = "Skogsvägen 69",
                            DepartmentId = 7,
                            FirstName = "Alexandrine",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 34036
                        },
                        new
                        {
                            Id = 46,
                            Address = "Adans Gata 98",
                            DepartmentId = 4,
                            FirstName = "Camylle",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 33657
                        },
                        new
                        {
                            Id = 47,
                            Address = "Benedicts Väg 966",
                            DepartmentId = 8,
                            FirstName = "Okey",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 45329
                        },
                        new
                        {
                            Id = 48,
                            Address = "Gustafssons Väg 1",
                            DepartmentId = 7,
                            FirstName = "Salvador",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 37583
                        },
                        new
                        {
                            Id = 49,
                            Address = "Undre Strandgränden 470",
                            DepartmentId = 2,
                            FirstName = "Cielo",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 41964
                        },
                        new
                        {
                            Id = 50,
                            Address = "Åkergatan 72",
                            DepartmentId = 9,
                            FirstName = "Merl",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 48165
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.HasOne("Labb2AngularAPI.Models.Person", null)
                        .WithMany("Department")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
