// <auto-generated />
using System;
using Labb2AngularAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AngularAPI.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20220926074953_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Smycken, Hälsa & Verktyg",
                            PersonId = 18
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spel",
                            PersonId = 17
                        },
                        new
                        {
                            Id = 3,
                            Name = "Böcker & Filmer",
                            PersonId = 40
                        },
                        new
                        {
                            Id = 4,
                            Name = "Smycken",
                            PersonId = 42
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sport",
                            PersonId = 10
                        },
                        new
                        {
                            Id = 6,
                            Name = "Leksaker & Hem",
                            PersonId = 21
                        },
                        new
                        {
                            Id = 7,
                            Name = "Livsmedel & Skor",
                            PersonId = 43
                        },
                        new
                        {
                            Id = 8,
                            Name = "Böcker & Hälsa",
                            PersonId = 7
                        },
                        new
                        {
                            Id = 9,
                            Name = "Verktyg, Skönhet & Skönhet",
                            PersonId = 50
                        },
                        new
                        {
                            Id = 10,
                            Name = "Skönhet",
                            PersonId = 32
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Loys Väg 731, Hatuna, Tjeckien",
                            DepartmentId = 4,
                            FirstName = "Lois",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 44369
                        },
                        new
                        {
                            Id = 2,
                            Address = "Idrottsgatan 6, Lyckstad, Nepal",
                            DepartmentId = 10,
                            FirstName = "Jeremy",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 52436
                        },
                        new
                        {
                            Id = 3,
                            Address = "Undre Skogsallén 886, Lyckmora, Komorerna",
                            DepartmentId = 6,
                            FirstName = "Luz",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 55997
                        },
                        new
                        {
                            Id = 4,
                            Address = "Parkvägen 8, Söderhamn, Egypten",
                            DepartmentId = 8,
                            FirstName = "Sedrick",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 38712
                        },
                        new
                        {
                            Id = 5,
                            Address = "Demarcos Gata 10, Enholm, Libanon",
                            DepartmentId = 6,
                            FirstName = "Jamarcus",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 56078
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kvarnvägen 6, Avmora, Estland",
                            DepartmentId = 10,
                            FirstName = "Destinee",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 35672
                        },
                        new
                        {
                            Id = 7,
                            Address = "Abbigails Väg 70, Enmora, Sudan",
                            DepartmentId = 2,
                            FirstName = "Cecile",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 44739
                        },
                        new
                        {
                            Id = 8,
                            Address = "Backgränden 966, Södervik, Israel",
                            DepartmentId = 3,
                            FirstName = "Johann",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 45985
                        },
                        new
                        {
                            Id = 9,
                            Address = "Anderssons Gata 704, Hafred, Samoa",
                            DepartmentId = 5,
                            FirstName = "Alyson",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 37000
                        },
                        new
                        {
                            Id = 10,
                            Address = "Annes Väg 46, Österholm, Pakistan",
                            DepartmentId = 8,
                            FirstName = "Bridgette",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 45902
                        },
                        new
                        {
                            Id = 11,
                            Address = "Erikssons Väg 92, Helsingmora, Bosnien och Hercegovina",
                            DepartmentId = 6,
                            FirstName = "Buster",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 46714
                        },
                        new
                        {
                            Id = 12,
                            Address = "Gustafssons Gata 4, Kungfors, Jamaica",
                            DepartmentId = 7,
                            FirstName = "Sophia",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 45607
                        },
                        new
                        {
                            Id = 13,
                            Address = "Wileys Gata 27, Båstad, Nordkorea",
                            DepartmentId = 1,
                            FirstName = "Doug",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 47363
                        },
                        new
                        {
                            Id = 14,
                            Address = "Nygränden 3, Gävmora, Mongoliet",
                            DepartmentId = 8,
                            FirstName = "Nicolette",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 44699
                        },
                        new
                        {
                            Id = 15,
                            Address = "Patricias Väg 710, Avlöv, Panama",
                            DepartmentId = 2,
                            FirstName = "Gudrun",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 55222
                        },
                        new
                        {
                            Id = 16,
                            Address = "Järnvägsallén 391, Alingholm, Vanuatu",
                            DepartmentId = 5,
                            FirstName = "Sydni",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 32294
                        },
                        new
                        {
                            Id = 17,
                            Address = "Aspallén 061, Eskfred, Israel",
                            DepartmentId = 2,
                            FirstName = "Ben",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 36564
                        },
                        new
                        {
                            Id = 18,
                            Address = "Perssons Väg 767, Karlvik, Malta",
                            DepartmentId = 9,
                            FirstName = "Faustino",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 38883
                        },
                        new
                        {
                            Id = 19,
                            Address = "Norra Ringvägen 2, Östersta, Zimbabwe",
                            DepartmentId = 1,
                            FirstName = "Dena",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 57804
                        },
                        new
                        {
                            Id = 20,
                            Address = "Östra Backgränden 95, Kunglöv, Finland",
                            DepartmentId = 3,
                            FirstName = "Dee",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 45269
                        },
                        new
                        {
                            Id = 21,
                            Address = "Södra Backgränden 882, Falhult, USA",
                            DepartmentId = 7,
                            FirstName = "Sabina",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 35429
                        },
                        new
                        {
                            Id = 22,
                            Address = "Västra Aspallén 9, Arfors, Dominica",
                            DepartmentId = 8,
                            FirstName = "Elza",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 39699
                        },
                        new
                        {
                            Id = 23,
                            Address = "Karlssons Väg 972, Gävberg, Ryssland",
                            DepartmentId = 5,
                            FirstName = "Patricia",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 39355
                        },
                        new
                        {
                            Id = 24,
                            Address = "Norra Ringgatan 82, Kramby, Fiji",
                            DepartmentId = 1,
                            FirstName = "Connor",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 37975
                        },
                        new
                        {
                            Id = 25,
                            Address = "Patiences Gata 68, Kramholm, El Salvador",
                            DepartmentId = 4,
                            FirstName = "Lulu",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 55147
                        },
                        new
                        {
                            Id = 26,
                            Address = "Östra Åkergärdet 288, Västhult, Mauretanien",
                            DepartmentId = 10,
                            FirstName = "Elouise",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 53127
                        },
                        new
                        {
                            Id = 27,
                            Address = "Larssons Väg 7, Falmora, Danmark",
                            DepartmentId = 1,
                            FirstName = "Irma",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 50639
                        },
                        new
                        {
                            Id = 28,
                            Address = "Stationsvägen 5, Karltuna, El Salvador",
                            DepartmentId = 6,
                            FirstName = "Llewellyn",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 58308
                        },
                        new
                        {
                            Id = 29,
                            Address = "Gustafssons Väg 7, Söderstad, Vanuatu",
                            DepartmentId = 1,
                            FirstName = "Adela",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 45413
                        },
                        new
                        {
                            Id = 30,
                            Address = "Jessikas Väg 96, Falberg, Nigeria",
                            DepartmentId = 3,
                            FirstName = "Bill",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 56461
                        },
                        new
                        {
                            Id = 31,
                            Address = "Genallén 8, Envik, Kanada",
                            DepartmentId = 10,
                            FirstName = "Chandler",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 57706
                        },
                        new
                        {
                            Id = 32,
                            Address = "Perssons Väg 494, Bovik, Danmark",
                            DepartmentId = 5,
                            FirstName = "Estefania",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 32461
                        },
                        new
                        {
                            Id = 33,
                            Address = "Skolgränden 304, Götemora, Centralafrikanska republiken",
                            DepartmentId = 6,
                            FirstName = "Lauretta",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 36005
                        },
                        new
                        {
                            Id = 34,
                            Address = "Undre Ringgärdet 98, Kungby, Samoa",
                            DepartmentId = 10,
                            FirstName = "Carlotta",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 50203
                        },
                        new
                        {
                            Id = 35,
                            Address = "Södra Furugatan 12, Väststad, Madagaskar",
                            DepartmentId = 2,
                            FirstName = "Norris",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 57710
                        },
                        new
                        {
                            Id = 36,
                            Address = "Dashawns Gata 271, Västås, Pakistan",
                            DepartmentId = 8,
                            FirstName = "Bryce",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 32068
                        },
                        new
                        {
                            Id = 37,
                            Address = "Skolgatan 924, Boås, Moçambique",
                            DepartmentId = 10,
                            FirstName = "Bella",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 41270
                        },
                        new
                        {
                            Id = 38,
                            Address = "Erikssons Gata 8, Österland, Kuwait",
                            DepartmentId = 8,
                            FirstName = "Toni",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 50548
                        },
                        new
                        {
                            Id = 39,
                            Address = "Larssons Väg 578, Kriststad, Haiti",
                            DepartmentId = 3,
                            FirstName = "Hanna",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 45510
                        },
                        new
                        {
                            Id = 40,
                            Address = "Gustafssons Väg 82, Kristtuna, Argentina",
                            DepartmentId = 3,
                            FirstName = "Camila",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 53090
                        },
                        new
                        {
                            Id = 41,
                            Address = "Undre Ekgatan 631, Helsingberg, Malawi",
                            DepartmentId = 6,
                            FirstName = "Joanie",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 55135
                        },
                        new
                        {
                            Id = 42,
                            Address = "Perssons Gata 09, Bosta, Antigua och Barbuda",
                            DepartmentId = 9,
                            FirstName = "Maya",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 52391
                        },
                        new
                        {
                            Id = 43,
                            Address = "Övre Fabriksvägen 68, Hahult, Elfenbenskusten",
                            DepartmentId = 4,
                            FirstName = "Hans",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 40000
                        },
                        new
                        {
                            Id = 44,
                            Address = "Granvägen 47, Kösta, Svalbard",
                            DepartmentId = 5,
                            FirstName = "Hayden",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 50190
                        },
                        new
                        {
                            Id = 45,
                            Address = "Södra Ekvägen 750, Esktuna, Sudan",
                            DepartmentId = 3,
                            FirstName = "Odessa",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 56005
                        },
                        new
                        {
                            Id = 46,
                            Address = "Erikssons Väg 3, Kungland, Malta",
                            DepartmentId = 5,
                            FirstName = "Cora",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 34473
                        },
                        new
                        {
                            Id = 47,
                            Address = "Östra Skolgränden 687, Falborg, Indonesien",
                            DepartmentId = 9,
                            FirstName = "Mina",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 56323
                        },
                        new
                        {
                            Id = 48,
                            Address = "Olssons Väg 90, Båby, Polen",
                            DepartmentId = 3,
                            FirstName = "Hertha",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 54970
                        },
                        new
                        {
                            Id = 49,
                            Address = "Emilianos Gata 184, Gävås, Saint Kitts och Nevis",
                            DepartmentId = 7,
                            FirstName = "Keagan",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 35464
                        },
                        new
                        {
                            Id = 50,
                            Address = "Beaus Väg 68, Brsås, Papua Nya Guinea",
                            DepartmentId = 6,
                            FirstName = "Roderick",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 49084
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.HasOne("Labb2AngularAPI.Models.Department", "Department")
                        .WithMany("Persons")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
