// <auto-generated />
using System;
using Labb2AngularAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AngularAPI.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20220926085130_fixdepartment")]
    partial class fixdepartment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Verktyg, Datorer & Datorer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Verktyg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Klädsel, Skor & Hem"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Datorer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Trädgård, Böcker & Smycken"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Trädgård, Musik & Filmer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Spel & Verktyg"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Skor"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Musik"
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Allens Väg 12",
                            DepartmentId = 7,
                            FirstName = "Otto",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 53724
                        },
                        new
                        {
                            Id = 2,
                            Address = "Trädgårdgärdet 26",
                            DepartmentId = 10,
                            FirstName = "Estevan",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 52483
                        },
                        new
                        {
                            Id = 3,
                            Address = "Karlssons Väg 5",
                            DepartmentId = 2,
                            FirstName = "Elisa",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 43971
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mazies Gata 391",
                            DepartmentId = 3,
                            FirstName = "Ethelyn",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 49293
                        },
                        new
                        {
                            Id = 5,
                            Address = "Aspgatan 5",
                            DepartmentId = 3,
                            FirstName = "Kylie",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 44243
                        },
                        new
                        {
                            Id = 6,
                            Address = "Donalds Gata 6",
                            DepartmentId = 1,
                            FirstName = "Veronica",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 41597
                        },
                        new
                        {
                            Id = 7,
                            Address = "Södra Aspvägen 37",
                            DepartmentId = 2,
                            FirstName = "Colin",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 39425
                        },
                        new
                        {
                            Id = 8,
                            Address = "Karlssons Gata 12",
                            DepartmentId = 2,
                            FirstName = "Eulalia",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 53117
                        },
                        new
                        {
                            Id = 9,
                            Address = "Olssons Väg 4",
                            DepartmentId = 3,
                            FirstName = "Ceasar",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 55814
                        },
                        new
                        {
                            Id = 10,
                            Address = "Erikssons Gata 252",
                            DepartmentId = 3,
                            FirstName = "Valentin",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 38792
                        },
                        new
                        {
                            Id = 11,
                            Address = "Franciscos Väg 04",
                            DepartmentId = 6,
                            FirstName = "Syble",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 42672
                        },
                        new
                        {
                            Id = 12,
                            Address = "Bäckgränden 54",
                            DepartmentId = 4,
                            FirstName = "Jonathan",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 34822
                        },
                        new
                        {
                            Id = 13,
                            Address = "Övre Industrigränden 119",
                            DepartmentId = 6,
                            FirstName = "Hiram",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 47221
                        },
                        new
                        {
                            Id = 14,
                            Address = "Larssons Väg 7",
                            DepartmentId = 7,
                            FirstName = "Richmond",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 32813
                        },
                        new
                        {
                            Id = 15,
                            Address = "Cristinas Gata 685",
                            DepartmentId = 10,
                            FirstName = "Alicia",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 55345
                        },
                        new
                        {
                            Id = 16,
                            Address = "Carrolls Väg 247",
                            DepartmentId = 8,
                            FirstName = "Polly",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 41230
                        },
                        new
                        {
                            Id = 17,
                            Address = "Horaces Gata 4",
                            DepartmentId = 10,
                            FirstName = "Cheyenne",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 39807
                        },
                        new
                        {
                            Id = 18,
                            Address = "Kyrkoallén 5",
                            DepartmentId = 5,
                            FirstName = "Vernice",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 54265
                        },
                        new
                        {
                            Id = 19,
                            Address = "Kvarngärdet 68",
                            DepartmentId = 4,
                            FirstName = "Caroline",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 41302
                        },
                        new
                        {
                            Id = 20,
                            Address = "Zoes Gata 585",
                            DepartmentId = 8,
                            FirstName = "Muriel",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 44566
                        },
                        new
                        {
                            Id = 21,
                            Address = "Olssons Gata 627",
                            DepartmentId = 7,
                            FirstName = "Everett",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 43760
                        },
                        new
                        {
                            Id = 22,
                            Address = "Erikssons Väg 716",
                            DepartmentId = 4,
                            FirstName = "Vergie",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 52140
                        },
                        new
                        {
                            Id = 23,
                            Address = "Västra Stationsallén 76",
                            DepartmentId = 10,
                            FirstName = "Brenden",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 43340
                        },
                        new
                        {
                            Id = 24,
                            Address = "Trädgårdgärdet 2",
                            DepartmentId = 8,
                            FirstName = "Marques",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 44610
                        },
                        new
                        {
                            Id = 25,
                            Address = "Västra Backgatan 05",
                            DepartmentId = 7,
                            FirstName = "Doris",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 33152
                        },
                        new
                        {
                            Id = 26,
                            Address = "Södra Furuallén 2",
                            DepartmentId = 8,
                            FirstName = "Omer",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 46518
                        },
                        new
                        {
                            Id = 27,
                            Address = "Västra Industriallén 641",
                            DepartmentId = 1,
                            FirstName = "Sunny",
                            Gender = 0,
                            LastName = "Nilsson",
                            Salary = 48653
                        },
                        new
                        {
                            Id = 28,
                            Address = "Karlssons Gata 094",
                            DepartmentId = 10,
                            FirstName = "Aiden",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 44981
                        },
                        new
                        {
                            Id = 29,
                            Address = "Dees Gata 976",
                            DepartmentId = 2,
                            FirstName = "Gerhard",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 55288
                        },
                        new
                        {
                            Id = 30,
                            Address = "Svenssons Gata 1",
                            DepartmentId = 4,
                            FirstName = "Cody",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 49223
                        },
                        new
                        {
                            Id = 31,
                            Address = "Skolvägen 290",
                            DepartmentId = 7,
                            FirstName = "Ari",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 49789
                        },
                        new
                        {
                            Id = 32,
                            Address = "Fabriksallén 596",
                            DepartmentId = 5,
                            FirstName = "Waldo",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 46096
                        },
                        new
                        {
                            Id = 33,
                            Address = "Merritts Gata 98",
                            DepartmentId = 10,
                            FirstName = "Jarrell",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 53600
                        },
                        new
                        {
                            Id = 34,
                            Address = "Olssons Väg 85",
                            DepartmentId = 8,
                            FirstName = "Pietro",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 37193
                        },
                        new
                        {
                            Id = 35,
                            Address = "Larssons Gata 7",
                            DepartmentId = 9,
                            FirstName = "Vernon",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 38955
                        },
                        new
                        {
                            Id = 36,
                            Address = "Övre Stationsgatan 938",
                            DepartmentId = 4,
                            FirstName = "Leann",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 51309
                        },
                        new
                        {
                            Id = 37,
                            Address = "Övre Villagärdet 40",
                            DepartmentId = 3,
                            FirstName = "Kyra",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 52546
                        },
                        new
                        {
                            Id = 38,
                            Address = "Övre Industrigränden 49",
                            DepartmentId = 2,
                            FirstName = "Newell",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 53952
                        },
                        new
                        {
                            Id = 39,
                            Address = "Ängsgatan 5",
                            DepartmentId = 9,
                            FirstName = "Clemmie",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 40541
                        },
                        new
                        {
                            Id = 40,
                            Address = "Erikssons Väg 10",
                            DepartmentId = 5,
                            FirstName = "Emerald",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 32064
                        },
                        new
                        {
                            Id = 41,
                            Address = "Undre Strandgatan 133",
                            DepartmentId = 5,
                            FirstName = "Bobbie",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 45200
                        },
                        new
                        {
                            Id = 42,
                            Address = "Maceys Väg 70",
                            DepartmentId = 1,
                            FirstName = "Deion",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 51085
                        },
                        new
                        {
                            Id = 43,
                            Address = "Östra Åkergränden 10",
                            DepartmentId = 7,
                            FirstName = "Chelsie",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 44664
                        },
                        new
                        {
                            Id = 44,
                            Address = "Roxannes Väg 851",
                            DepartmentId = 4,
                            FirstName = "Ian",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 32647
                        },
                        new
                        {
                            Id = 45,
                            Address = "Grangatan 7",
                            DepartmentId = 4,
                            FirstName = "Quinten",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 58749
                        },
                        new
                        {
                            Id = 46,
                            Address = "Undre Åkergatan 77",
                            DepartmentId = 2,
                            FirstName = "Sigurd",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 37150
                        },
                        new
                        {
                            Id = 47,
                            Address = "Verlies Väg 651",
                            DepartmentId = 9,
                            FirstName = "Deven",
                            Gender = 0,
                            LastName = "Johansson",
                            Salary = 45363
                        },
                        new
                        {
                            Id = 48,
                            Address = "Västra Storvägen 445",
                            DepartmentId = 10,
                            FirstName = "Rhett",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 47522
                        },
                        new
                        {
                            Id = 49,
                            Address = "Wiltons Väg 916",
                            DepartmentId = 4,
                            FirstName = "Alfred",
                            Gender = 0,
                            LastName = "Andersson",
                            Salary = 44347
                        },
                        new
                        {
                            Id = 50,
                            Address = "Houstons Gata 054",
                            DepartmentId = 9,
                            FirstName = "Moriah",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 48167
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.HasOne("Labb2AngularAPI.Models.Person", "Person")
                        .WithMany("Department")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
