// <auto-generated />
using System;
using Labb2AngularAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2AngularAPI.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Skor, Skor & Verktyg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hälsa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hem & Skönhet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Musik, Klädsel & Smycken"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Spel & Filmer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Skor, Klädsel & Hälsa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Leksaker"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Livsmedel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Böcker, Klädsel & Livsmedel"
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Larssons Gata 1",
                            DepartmentId = 8,
                            FirstName = "Ashtyn",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 44064
                        },
                        new
                        {
                            Id = 2,
                            Address = "Domenicks Väg 0",
                            DepartmentId = 5,
                            FirstName = "Aletha",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 50869
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kyrkovägen 129",
                            DepartmentId = 9,
                            FirstName = "Isaiah",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 54207
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ringgatan 8",
                            DepartmentId = 3,
                            FirstName = "Roberta",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 48260
                        },
                        new
                        {
                            Id = 5,
                            Address = "Undre Bäckgatan 25",
                            DepartmentId = 8,
                            FirstName = "Lonzo",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 44361
                        },
                        new
                        {
                            Id = 6,
                            Address = "Austins Väg 1",
                            DepartmentId = 1,
                            FirstName = "Raphaelle",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 56208
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ekgatan 64",
                            DepartmentId = 6,
                            FirstName = "Darius",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 34099
                        },
                        new
                        {
                            Id = 8,
                            Address = "Stationsallén 7",
                            DepartmentId = 2,
                            FirstName = "Brielle",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 35261
                        },
                        new
                        {
                            Id = 9,
                            Address = "Gengärdet 94",
                            DepartmentId = 2,
                            FirstName = "Moises",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 33118
                        },
                        new
                        {
                            Id = 10,
                            Address = "Candelarios Väg 406",
                            DepartmentId = 10,
                            FirstName = "Katelyn",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 54619
                        },
                        new
                        {
                            Id = 11,
                            Address = "Erikssons Gata 147",
                            DepartmentId = 4,
                            FirstName = "Columbus",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 32174
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kyrkogränden 238",
                            DepartmentId = 2,
                            FirstName = "Aisha",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 46736
                        },
                        new
                        {
                            Id = 13,
                            Address = "Mortons Väg 8",
                            DepartmentId = 10,
                            FirstName = "Queen",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 36662
                        },
                        new
                        {
                            Id = 14,
                            Address = "Östra Idrottsgränden 92",
                            DepartmentId = 3,
                            FirstName = "Bruce",
                            Gender = 1,
                            LastName = "Nilsson",
                            Salary = 34469
                        },
                        new
                        {
                            Id = 15,
                            Address = "Norra Villavägen 23",
                            DepartmentId = 5,
                            FirstName = "Jazmin",
                            Gender = 0,
                            LastName = "Larsson",
                            Salary = 50831
                        },
                        new
                        {
                            Id = 16,
                            Address = "Daphnees Gata 9",
                            DepartmentId = 3,
                            FirstName = "Tito",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 36732
                        },
                        new
                        {
                            Id = 17,
                            Address = "Östra Björkgärdet 0",
                            DepartmentId = 8,
                            FirstName = "Adrienne",
                            Gender = 1,
                            LastName = "Andersson",
                            Salary = 40735
                        },
                        new
                        {
                            Id = 18,
                            Address = "Stanfords Gata 2",
                            DepartmentId = 2,
                            FirstName = "Myles",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 40567
                        },
                        new
                        {
                            Id = 19,
                            Address = "Francescos Gata 81",
                            DepartmentId = 4,
                            FirstName = "Waylon",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 55698
                        },
                        new
                        {
                            Id = 20,
                            Address = "Övre Aspgränden 593",
                            DepartmentId = 3,
                            FirstName = "Rashawn",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 44283
                        },
                        new
                        {
                            Id = 21,
                            Address = "Undre Ängsgränden 7",
                            DepartmentId = 10,
                            FirstName = "Deon",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 44905
                        },
                        new
                        {
                            Id = 22,
                            Address = "Gustafssons Gata 01",
                            DepartmentId = 3,
                            FirstName = "Kayley",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 49037
                        },
                        new
                        {
                            Id = 23,
                            Address = "Erikssons Gata 80",
                            DepartmentId = 3,
                            FirstName = "Reuben",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 50897
                        },
                        new
                        {
                            Id = 24,
                            Address = "Karlssons Gata 45",
                            DepartmentId = 5,
                            FirstName = "Addie",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 34953
                        },
                        new
                        {
                            Id = 25,
                            Address = "Erikssons Väg 180",
                            DepartmentId = 1,
                            FirstName = "Jay",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 41650
                        },
                        new
                        {
                            Id = 26,
                            Address = "Kyrkogränden 337",
                            DepartmentId = 3,
                            FirstName = "Raheem",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 43810
                        },
                        new
                        {
                            Id = 27,
                            Address = "Aspgränden 41",
                            DepartmentId = 5,
                            FirstName = "Cornelius",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 58064
                        },
                        new
                        {
                            Id = 28,
                            Address = "Furugränden 2",
                            DepartmentId = 3,
                            FirstName = "Estel",
                            Gender = 1,
                            LastName = "Olsson",
                            Salary = 55654
                        },
                        new
                        {
                            Id = 29,
                            Address = "Perssons Gata 89",
                            DepartmentId = 7,
                            FirstName = "Maryam",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 43193
                        },
                        new
                        {
                            Id = 30,
                            Address = "Gustafssons Gata 7",
                            DepartmentId = 10,
                            FirstName = "Dorcas",
                            Gender = 0,
                            LastName = "Olsson",
                            Salary = 39737
                        },
                        new
                        {
                            Id = 31,
                            Address = "Undre Aspgärdet 43",
                            DepartmentId = 6,
                            FirstName = "Jennings",
                            Gender = 1,
                            LastName = "Larsson",
                            Salary = 35503
                        },
                        new
                        {
                            Id = 32,
                            Address = "Anderssons Gata 667",
                            DepartmentId = 5,
                            FirstName = "Charley",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 45334
                        },
                        new
                        {
                            Id = 33,
                            Address = "Heloises Gata 7",
                            DepartmentId = 3,
                            FirstName = "Ryann",
                            Gender = 0,
                            LastName = "Karlsson",
                            Salary = 52604
                        },
                        new
                        {
                            Id = 34,
                            Address = "Hillards Gata 5",
                            DepartmentId = 1,
                            FirstName = "Novella",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 48278
                        },
                        new
                        {
                            Id = 35,
                            Address = "Idrottsgränden 038",
                            DepartmentId = 4,
                            FirstName = "Lloyd",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 53489
                        },
                        new
                        {
                            Id = 36,
                            Address = "Skogsallén 11",
                            DepartmentId = 9,
                            FirstName = "Keyon",
                            Gender = 0,
                            LastName = "Eriksson",
                            Salary = 34308
                        },
                        new
                        {
                            Id = 37,
                            Address = "Järnvägsallén 42",
                            DepartmentId = 10,
                            FirstName = "Susan",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 41746
                        },
                        new
                        {
                            Id = 38,
                            Address = "Strandallén 2",
                            DepartmentId = 8,
                            FirstName = "Colt",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 36065
                        },
                        new
                        {
                            Id = 39,
                            Address = "Tierras Gata 529",
                            DepartmentId = 8,
                            FirstName = "Anahi",
                            Gender = 0,
                            LastName = "Persson",
                            Salary = 41561
                        },
                        new
                        {
                            Id = 40,
                            Address = "Perssons Gata 740",
                            DepartmentId = 3,
                            FirstName = "Gregoria",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 41946
                        },
                        new
                        {
                            Id = 41,
                            Address = "Perssons Gata 4",
                            DepartmentId = 7,
                            FirstName = "Darrick",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 51974
                        },
                        new
                        {
                            Id = 42,
                            Address = "Perssons Gata 21",
                            DepartmentId = 1,
                            FirstName = "Naomi",
                            Gender = 1,
                            LastName = "Eriksson",
                            Salary = 53879
                        },
                        new
                        {
                            Id = 43,
                            Address = "Södra Villagärdet 618",
                            DepartmentId = 10,
                            FirstName = "Hassie",
                            Gender = 1,
                            LastName = "Karlsson",
                            Salary = 56740
                        },
                        new
                        {
                            Id = 44,
                            Address = "Freedas Gata 7",
                            DepartmentId = 8,
                            FirstName = "Elody",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 54048
                        },
                        new
                        {
                            Id = 45,
                            Address = "Östra Stationsgärdet 894",
                            DepartmentId = 6,
                            FirstName = "Alanna",
                            Gender = 0,
                            LastName = "Gustafsson",
                            Salary = 40354
                        },
                        new
                        {
                            Id = 46,
                            Address = "Ringgatan 87",
                            DepartmentId = 7,
                            FirstName = "Nestor",
                            Gender = 1,
                            LastName = "Johansson",
                            Salary = 36116
                        },
                        new
                        {
                            Id = 47,
                            Address = "Södra Ekgatan 3",
                            DepartmentId = 8,
                            FirstName = "Yasmeen",
                            Gender = 1,
                            LastName = "Svensson",
                            Salary = 44871
                        },
                        new
                        {
                            Id = 48,
                            Address = "Everettes Gata 169",
                            DepartmentId = 7,
                            FirstName = "Branson",
                            Gender = 1,
                            LastName = "Gustafsson",
                            Salary = 54538
                        },
                        new
                        {
                            Id = 49,
                            Address = "Storgärdet 169",
                            DepartmentId = 6,
                            FirstName = "Carole",
                            Gender = 0,
                            LastName = "Svensson",
                            Salary = 40545
                        },
                        new
                        {
                            Id = 50,
                            Address = "Lethas Väg 11",
                            DepartmentId = 10,
                            FirstName = "Jana",
                            Gender = 1,
                            LastName = "Persson",
                            Salary = 43744
                        });
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Department", b =>
                {
                    b.HasOne("Labb2AngularAPI.Models.Person", "Person")
                        .WithMany("Department")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb2AngularAPI.Models.Person", b =>
                {
                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
